### ISSUE TITLE
Switch to Etherpad Lite

### ISSUE THREAD

**Issue by mnoorenberghe** [toolness/htmlpad#1]
Hey Atul,

Mozilla switched to Etherpad Lite (now at https://public.etherpad-mozilla.org/ ) so htmlpad.org is no longer working and I miss it since other similar tools like jsfiddle's collaboration are buggy or are more complex. If I submit a patch to make it work with the new site, would you accept it?

**Comment by toolness** [comment]
Oh sure, I'd be happy to accept it!

I should note that I don't work at Mozilla anymore... I don't think this has any bearing on htmlpad.org, as that whole domain is still under my control--it's been so long since I've used it that I just had to double-check--so I _think_ this means that I'd be able to make your changes go live on htmlpad.org. But there's a small chance that I'm forgetting something and that your work would be all for naught, at least as far as htmlpad.org goes. Just want to make sure you know!

**Comment by mnoorenberghe** [comment]
> Oh sure, I'd be happy to accept it!

Great, do you care to support both old Etherpad and Etherpad Lite or can I replace the URL paths with EP Lite ones? My possibly outdated understanding is that Etherpad is no longer maintained and may have security issues so Etherpad Lite is what everyone uses now.

> I should note that I don't work at Mozilla anymore... 

Yeah, I realized this the other night :(

> I don't think this has any bearing on htmlpad.org, as that whole domain is still under my control--it's been so long since I've used it that I just had to double-check--so I think this means that I'd be able to make your changes go live on htmlpad.org. But there's a small chance that I'm forgetting something and that your work would be all for naught, at least as far as htmlpad.org goes. Just want to make sure you know!

Are you saying that there might be some dependency on Mozilla access to deploy changes or something else? I still work for Mozilla so could probably help with that. I can also help with hosting if you need.

**Comment by toolness** [comment]
Oh nice! Help with hosting could be great--right now htmlpad.org is actually hosted by Heroku, and ever since they migrated to their [recharging](https://devcenter.heroku.com/articles/dyno-sleeping#recharging) model for free dynos, I've actually received a few emails telling them that htmlpad needed to recharge! So moving it to Mozilla's heroku account and being given the standard $7.99/month plan or whatever could be nice.

I'm also happy to stop supporting the original Etherpad, it seems like nobody uses it anymore...

As yet another alternative, if you're more comfortable with nodeJS than Python, you're also welcome to re-implement htmlpad using that...  I'm not even sure if Node really existed at the time that I originally wrote htmlpad in mid-2010, but because of how simple the app architecture is, I bet it would be a lot more performant if it moved to node. Anyways, that's probably too much work--I just wanted to let you know I'm totally open to it in case you were thinking along similar lines.

**Comment by mnoorenberghe** [comment]
I'm actually more familiar with Django than Node so I think I'll just make the fix on the current architecture.

I'll look into hosting after I have the patch. I actually haven't used Heroku yet, only Mozilla's previous PAAS thing which got shutdown. I also just host stuff on my own dedicated server.
